services:
  invoice_automator:
    image: invoice-automator:latest
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      - FIBERY_API_TOKEN=${FIBERY_API_TOKEN}
      - MONEYBIRD_API_TOKEN=${MONEYBIRD_API_TOKEN}